name: Preview

on: [pull_request]

jobs:
  preview:
    runs-on: self-hosted
    env:
      HUGO_VERSION: 0.62.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Check environment
        run: |
          echo "HUGO_PATH=`which hugo`" >> $GITHUB_ENV

      - name: Setup Hugo
        if: ${{ env.HUGO_PATH == '' }}
        run: |
          apt-get update
          apt-get install golang
          
          cd `mktemp -d`
          wget https://github.com/gohugoio/hugo/archive/refs/tags/v${HUGO_VERSION}.tar.gz
          cd hugo-${HUGO_VERSION}
          CGO_ENABLED=1 go install --tags extended

      - name: Configure
        run: |
          sed -i -E "s/^baseURL ?=.+$/baseURL = '${GITHUB_SHA}'/g" ./config.toml
          sed -i -E "s/^google_analitycs_id ?=.+$/google_analitycs_id = ''/g" ./config.toml

      - name: Build and deploy
        run: |
          echo ${GITHUB_SHA}
          hugo --gc --minify --cleanDestinationDir
          mv public /var/www/html/${GITHUB_SHA}
