name: Preview

on: [pull_request]

jobs:
  preview:
    runs-on: self-hosted
    env:
      HUGO_VERSION: 0.62.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check environment
        run: |
          echo "HUGO_PATH=`which hugo`" >> $GITHUB_ENV

      - name: Setup Hugo
        if: ${{ env.HUGO_PATH == '' }}
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-ARM64.deb
          # wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-ARM64.deb
          apt-get -y install ./hugo_${HUGO_VERSION}_Linux-ARM64.deb && \
          # apt-get -y install ./hugo_extended_${HUGO_VERSION}_Linux-ARM64.deb && \
          # rm hugo_${HUGO_VERSION}_Linux-ARM64.deb hugo_extended_${HUGO_VERSION}_Linux-ARM64.deb
          rm hugo_${HUGO_VERSION}_Linux-ARM64.deb

      - name: Configure
        run: |
          sed -i -E "s/^baseURL ?=.+$/baseURL = '${GITHUB_SHA}'/g" ./config.toml
          sed -i -E "s/^google_analitycs_id ?=.+$/google_analitycs_id = ''/g" ./config.toml

      - name: Build and deploy
        run: |
          echo ${GITHUB_SHA}
          hugo --gc --minify --cleanDestinationDir
          mv public /var/www/html/${GITHUB_SHA}
